version: '3'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${MYSQL_DB_DB}
      POSTGRES_PASSWORD: ${SQL_ROOT_PASSWORD}
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "3305:8080"
  keycloak:
    depends_on:
      - db
    container_name: local_keycloak
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: ${MYSQL_DB_DB}
      DB_USER: ${MYSQL_DB_USERNAME}
      DB_PASSWORD: ${SQL_ROOT_PASSWORD}
      KEYCLOAK_ADMIN: ad
      KEYCLOAK_ADMIN_PASSWORD: 1488
    image: quay.io/keycloak/keycloak
    command:
      - start-dev
    ports:
      - "28080:8080"
    restart: always