version: '3'

services:
  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${MYSQL_DB_DB}
      POSTGRES_PASSWORD: ${SQL_ROOT_PASSWORD}
    ports:
      - "5432:5432"
  adminer:
    image: adminer
    restart: always
    ports:
      - "3305:8080"
  vplyas:
    build: .
    ports:
      - "80:81"