version: '3'

services:
  db:
    container_name: db
    image: mysql
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  adminer:
    image: adminer
    restart: always
    ports:
      - "3305:8080"
  vplyas:
    build: .
    ports:
      - "80:80"


